//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRaPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class education
    {
        public int id { get; set; }
        public string empID { get; set; }
        public Nullable<int> nLevel { get; set; }
        public string name_of_school { get; set; }
        public string degree_course { get; set; }
        public string year_graduated { get; set; }
        public string units_earned { get; set; }
        public Nullable<System.DateTime> dFrom { get; set; }
        public Nullable<System.DateTime> dTo { get; set; }
        public string honors_received { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
