//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRaPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class eligibility
    {
        public int id { get; set; }
        public string empID { get; set; }
        public string career_service { get; set; }
        public string rating { get; set; }
        public Nullable<System.DateTime> date_examination { get; set; }
        public string place_of_examination { get; set; }
        public string license_no { get; set; }
        public Nullable<System.DateTime> date_release { get; set; }
    }
}
