//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRaPS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class HRaPSEntities : DbContext
    {
        public HRaPSEntities()
            : base("name=HRaPSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<child> children { get; set; }
        public DbSet<civil_status> civil_status { get; set; }
        public DbSet<division> divisions { get; set; }
        public DbSet<education> educations { get; set; }
        public DbSet<eligibility> eligibilities { get; set; }
        public DbSet<gender> genders { get; set; }
        public DbSet<information> information { get; set; }
        public DbSet<information_type> information_type { get; set; }
        public DbSet<other_information> other_information { get; set; }
        public DbSet<position> positions { get; set; }
        public DbSet<status> status { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<training> trainings { get; set; }
        public DbSet<voluntary_work> voluntary_work { get; set; }
        public DbSet<work_experience> work_experience { get; set; }
    
        public virtual ObjectResult<hr_view_employee_view_civil_status_Result> hr_view_employee_view_civil_status()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hr_view_employee_view_civil_status_Result>("hr_view_employee_view_civil_status");
        }
    
        public virtual ObjectResult<hr_view_employee_view_division_Result> hr_view_employee_view_division()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hr_view_employee_view_division_Result>("hr_view_employee_view_division");
        }
    
        public virtual ObjectResult<hr_view_employee_view_gender_Result> hr_view_employee_view_gender()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hr_view_employee_view_gender_Result>("hr_view_employee_view_gender");
        }
    
        public virtual ObjectResult<hr_view_employee_view_status_Result> hr_view_employee_view_status()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<hr_view_employee_view_status_Result>("hr_view_employee_view_status");
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int hr_view_employee_new_information(string empID, Nullable<int> division_id, Nullable<int> status_id, string fName, string mName, string lName, string eName, Nullable<System.DateTime> birthdate, string place_of_birth, Nullable<int> sex, Nullable<int> civil_status, string citizenship, string height, string weight, string blood_type, string gsis, string pagibig, string philhealth, string sss, string res_address, string res_zip_code, string res_tel, string perma_address, string perma_zip_code, string perma_tel, string email, string cellphone_no, string tin, string username)
        {
            var empIDParameter = empID != null ?
                new ObjectParameter("empID", empID) :
                new ObjectParameter("empID", typeof(string));
    
            var division_idParameter = division_id.HasValue ?
                new ObjectParameter("division_id", division_id) :
                new ObjectParameter("division_id", typeof(int));
    
            var status_idParameter = status_id.HasValue ?
                new ObjectParameter("status_id", status_id) :
                new ObjectParameter("status_id", typeof(int));
    
            var fNameParameter = fName != null ?
                new ObjectParameter("fName", fName) :
                new ObjectParameter("fName", typeof(string));
    
            var mNameParameter = mName != null ?
                new ObjectParameter("mName", mName) :
                new ObjectParameter("mName", typeof(string));
    
            var lNameParameter = lName != null ?
                new ObjectParameter("lName", lName) :
                new ObjectParameter("lName", typeof(string));
    
            var eNameParameter = eName != null ?
                new ObjectParameter("eName", eName) :
                new ObjectParameter("eName", typeof(string));
    
            var birthdateParameter = birthdate.HasValue ?
                new ObjectParameter("birthdate", birthdate) :
                new ObjectParameter("birthdate", typeof(System.DateTime));
    
            var place_of_birthParameter = place_of_birth != null ?
                new ObjectParameter("place_of_birth", place_of_birth) :
                new ObjectParameter("place_of_birth", typeof(string));
    
            var sexParameter = sex.HasValue ?
                new ObjectParameter("sex", sex) :
                new ObjectParameter("sex", typeof(int));
    
            var civil_statusParameter = civil_status.HasValue ?
                new ObjectParameter("civil_status", civil_status) :
                new ObjectParameter("civil_status", typeof(int));
    
            var citizenshipParameter = citizenship != null ?
                new ObjectParameter("citizenship", citizenship) :
                new ObjectParameter("citizenship", typeof(string));
    
            var heightParameter = height != null ?
                new ObjectParameter("height", height) :
                new ObjectParameter("height", typeof(string));
    
            var weightParameter = weight != null ?
                new ObjectParameter("weight", weight) :
                new ObjectParameter("weight", typeof(string));
    
            var blood_typeParameter = blood_type != null ?
                new ObjectParameter("blood_type", blood_type) :
                new ObjectParameter("blood_type", typeof(string));
    
            var gsisParameter = gsis != null ?
                new ObjectParameter("gsis", gsis) :
                new ObjectParameter("gsis", typeof(string));
    
            var pagibigParameter = pagibig != null ?
                new ObjectParameter("pagibig", pagibig) :
                new ObjectParameter("pagibig", typeof(string));
    
            var philhealthParameter = philhealth != null ?
                new ObjectParameter("philhealth", philhealth) :
                new ObjectParameter("philhealth", typeof(string));
    
            var sssParameter = sss != null ?
                new ObjectParameter("sss", sss) :
                new ObjectParameter("sss", typeof(string));
    
            var res_addressParameter = res_address != null ?
                new ObjectParameter("res_address", res_address) :
                new ObjectParameter("res_address", typeof(string));
    
            var res_zip_codeParameter = res_zip_code != null ?
                new ObjectParameter("res_zip_code", res_zip_code) :
                new ObjectParameter("res_zip_code", typeof(string));
    
            var res_telParameter = res_tel != null ?
                new ObjectParameter("res_tel", res_tel) :
                new ObjectParameter("res_tel", typeof(string));
    
            var perma_addressParameter = perma_address != null ?
                new ObjectParameter("perma_address", perma_address) :
                new ObjectParameter("perma_address", typeof(string));
    
            var perma_zip_codeParameter = perma_zip_code != null ?
                new ObjectParameter("perma_zip_code", perma_zip_code) :
                new ObjectParameter("perma_zip_code", typeof(string));
    
            var perma_telParameter = perma_tel != null ?
                new ObjectParameter("perma_tel", perma_tel) :
                new ObjectParameter("perma_tel", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var cellphone_noParameter = cellphone_no != null ?
                new ObjectParameter("cellphone_no", cellphone_no) :
                new ObjectParameter("cellphone_no", typeof(string));
    
            var tinParameter = tin != null ?
                new ObjectParameter("tin", tin) :
                new ObjectParameter("tin", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("hr_view_employee_new_information", empIDParameter, division_idParameter, status_idParameter, fNameParameter, mNameParameter, lNameParameter, eNameParameter, birthdateParameter, place_of_birthParameter, sexParameter, civil_statusParameter, citizenshipParameter, heightParameter, weightParameter, blood_typeParameter, gsisParameter, pagibigParameter, philhealthParameter, sssParameter, res_addressParameter, res_zip_codeParameter, res_telParameter, perma_addressParameter, perma_zip_codeParameter, perma_telParameter, emailParameter, cellphone_noParameter, tinParameter, usernameParameter);
        }
    }
}
