//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRaPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class information
    {
        public int id { get; set; }
        public string empID { get; set; }
        public string fName { get; set; }
        public string mName { get; set; }
        public string lName { get; set; }
        public string eName { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string place_of_birth { get; set; }
        public Nullable<int> sex { get; set; }
        public Nullable<int> civil_status { get; set; }
        public string citizenship { get; set; }
        public string height { get; set; }
        public string weight { get; set; }
        public string blood_type { get; set; }
        public string gsis { get; set; }
        public string pagibig { get; set; }
        public string philhealth { get; set; }
        public string sss { get; set; }
        public string res_address { get; set; }
        public string res_zip_code { get; set; }
        public string res_tel { get; set; }
        public string perma_address { get; set; }
        public string perma_zip_code { get; set; }
        public string perma_tel { get; set; }
        public string email { get; set; }
        public string cellphone_no { get; set; }
        public string tin { get; set; }
        public string s_fName { get; set; }
        public string s_mName { get; set; }
        public string s_lName { get; set; }
        public string s_occupation { get; set; }
        public string s_employer_name { get; set; }
        public string s_bus_address { get; set; }
        public string s_tel { get; set; }
        public string f_fName { get; set; }
        public string f_mName { get; set; }
        public string f_lName { get; set; }
        public string m_fName { get; set; }
        public string m_mName { get; set; }
        public string m_lName { get; set; }
        public string ctc_no { get; set; }
        public string issued_at { get; set; }
        public string issued_on { get; set; }
        public Nullable<System.DateTime> date_accomplished { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> division_id { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public string username { get; set; }
        public Nullable<int> nConfirm { get; set; }
        public Nullable<int> nDelete { get; set; }
    }
}
