//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRaPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class work_experience
    {
        public int id { get; set; }
        public string empID { get; set; }
        public Nullable<System.DateTime> dFrom { get; set; }
        public Nullable<System.DateTime> dTo { get; set; }
        public Nullable<int> positionID { get; set; }
        public Nullable<int> division_id { get; set; }
        public Nullable<decimal> salary { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
